# Generated by Django 4.2.16 on 2025-03-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customelephantuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customelephantuser',
            name='login',
        ),
        migrations.AlterField(
            model_name='customelephantuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
