# Generated by Django 4.2.16 on 2024-11-03 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=511)),
                ('dropoff_location', models.CharField(max_length=511)),
                ('pickup_time', models.DateTimeField()),
                ('dropoff_time', models.DateTimeField()),
                ('renter_name', models.CharField(max_length=255)),
                ('renter_birthdate', models.DateField()),
                ('renter_phone', models.CharField(max_length=20)),
                ('renter_email', models.EmailField(max_length=254)),
                ('contact_method', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('viber', 'Viber')], max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('bid_preparer', models.CharField(max_length=127)),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_booked', models.BooleanField(default=False)),
                ('insurance', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('state_number', models.CharField(max_length=63)),
                ('slug', models.SlugField(max_length=127, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='cars/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands_in_car', to='backend.brand')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_one', models.DecimalField(decimal_places=2, max_digits=10)),
                ('season_two', models.DecimalField(decimal_places=2, max_digits=10)),
                ('season_three', models.DecimalField(decimal_places=2, max_digits=10)),
                ('season_four', models.DecimalField(decimal_places=2, max_digits=10)),
                ('season_one_upto7', models.DecimalField(decimal_places=2, max_digits=10)),
                ('season_two_upto7', models.DecimalField(decimal_places=2, max_digits=10)),
                ('season_three_upto7', models.DecimalField(decimal_places=2, max_digits=10)),
                ('season_four_upto7', models.DecimalField(decimal_places=2, max_digits=10)),
                ('season_one_upto14', models.DecimalField(decimal_places=2, max_digits=10)),
                ('season_two_upto14', models.DecimalField(decimal_places=2, max_digits=10)),
                ('season_three_upto14', models.DecimalField(decimal_places=2, max_digits=10)),
                ('season_four_upto14', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='backend.car')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='backend_mod_name_c565f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Investor',
                'verbose_name_plural': 'Investors',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='backend_inv_name_8a324a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='backend_col_name_0da9f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='backend_cat_name_4dc900_idx')],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='backend.category'),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='backend.color'),
        ),
        migrations.AddField(
            model_name='car',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investors', to='backend.investor'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models_in_car', to='backend.model'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['name'], name='backend_bra_name_a04424_idx'),
        ),
        migrations.AddField(
            model_name='bid',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='backend.car'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['brand'], name='backend_car_brand_i_17eecf_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['-created_at'], name='backend_car_created_ed09e7_idx'),
        ),
    ]
