# Generated by Django 4.2.16 on 2024-11-04 10:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='model', unique=True),
        ),
    ]
