# Generated by Django 4.2.16 on 2024-11-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='contract_dir'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='vaucher',
            field=models.FileField(blank=True, null=True, upload_to='vaucher_dir'),
        ),
    ]
