# Generated by Django 4.2.16 on 2024-11-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_bid_contract_alter_bid_vaucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='other_files'),
        ),
    ]
