# Generated by Django 4.2.16 on 2025-01-16 18:19

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_investor_alter_car_investor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=512)),
                ('dropoff_location', models.CharField(max_length=512)),
                ('pickup_time', models.DateTimeField()),
                ('dropoff_time', models.DateTimeField()),
                ('renter_name', models.CharField(max_length=128)),
                ('renter_phone', models.CharField(max_length=32)),
                ('renter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=128)),
                ('start_date', models.DateTimeField()),
                ('expired_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'insurance',
                'verbose_name_plural': 'insurances',
                'ordering': ['symbol'],
            },
        ),
        migrations.RemoveField(
            model_name='bid',
            name='car',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='price',
        ),
        migrations.AlterModelManagers(
            name='car',
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='car',
            name='backend_car_brand_i_17eecf_idx',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='is_booked',
            new_name='is_availaible',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='season_four',
            new_name='autumn_price',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='season_one',
            new_name='spring_price',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='season_three',
            new_name='summer_price',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='season_two',
            new_name='winter_price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.RemoveField(
            model_name='car',
            name='state_number',
        ),
        migrations.RemoveField(
            model_name='model',
            name='brand',
        ),
        migrations.AddField(
            model_name='car',
            name='car_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='year_manufactored',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='currency',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='model', unique=True),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['car_name'], name='backend_car_car_nam_1d6c2c_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['is_availaible'], name='backend_car_is_avai_c39eee_idx'),
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.AddIndex(
            model_name='insurance',
            index=models.Index(fields=['symbol'], name='backend_ins_symbol_4d237f_idx'),
        ),
        migrations.AddField(
            model_name='application',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='backend.car'),
        ),
        migrations.AddField(
            model_name='application',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests_price', to='backend.price'),
        ),
        migrations.AlterField(
            model_name='car',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_insurance', to='backend.insurance'),
        ),
    ]
