# Generated by Django 4.2.16 on 2024-11-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_bidfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contract_in_bid', to='backend.bidfiles'),
            preserve_default=False,
        ),
    ]
