# Generated by Django 4.2.16 on 2025-01-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_application_insurance_remove_bid_car_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='car',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_expired',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('canceled', 'Canceled'), ('expired', 'Expired'), ('active', 'Active')], max_length=16),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='symbol',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
