# Generated by Django 4.2.16 on 2024-11-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_bid_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='doc',
            field=models.FileField(default=1, upload_to='uploads_model'),
            preserve_default=False,
        ),
    ]
