# Generated by Django 4.2.16 on 2024-11-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_bid_bid_preparer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_preparer',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
