# Generated by Django 4.2.16 on 2025-01-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_car_managers_remove_application_is_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='aggregator',
            field=models.CharField(blank=True, choices=[('aggregator1', 'Aggregator 1'), ('aggregator2', 'Aggregator 2'), ('aggregator3', 'Aggregator 3')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='aggregator_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='application_preparer',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
