# Generated by Django 4.2.16 on 2024-11-14 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_bid_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_in_bid', to='backend.bidfiles'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='doc',
            field=models.FileField(null=True, upload_to='uploads_model'),
        ),
    ]
