# Generated by Django 4.2.16 on 2024-11-18 19:39

import backend.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_files_alter_bid_bid_preparer_bid_other_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='other_files',
        ),
        migrations.AddField(
            model_name='files',
            name='bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='backend.bid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=backend.validators.other_files_path),
        ),
    ]
