# Generated by Django 4.2.16 on 2024-11-20 15:15

import backend.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_files_alter_bid_bid_preparer_bid_other_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='other_files',
        ),
        migrations.AddField(
            model_name='bid',
            name='car_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='backend.bid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='backend.car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investors', to='backend.investor'),
        ),
        migrations.AlterField(
            model_name='files',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=backend.utils.other_files_path),
        ),
    ]
