# Generated by Django 4.2.16 on 2024-11-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_bid_other_files_bid_car_info_files_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
