# Generated by Django 4.2.16 on 2024-11-18 13:11

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_bid_other_files_files_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=backend.validators.other_files_path),
        ),
    ]
