# Generated by Django 4.2.16 on 2024-11-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_files_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
