# Generated by Django 4.2.16 on 2025-01-21 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_problem_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='car_problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_car', to='backend.car'),
        ),
    ]
