# Generated by Django 4.2.16 on 2024-11-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_bid_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
