# Generated by Django 4.2.16 on 2025-01-22 18:45

import backend.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_problem_car_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='contract_dir'),
        ),
        migrations.AddField(
            model_name='application',
            name='vaucher',
            field=models.FileField(blank=True, null=True, upload_to='vaucher_dir'),
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to=backend.utils.other_files_path)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='backend.application')),
            ],
        ),
    ]
