# Generated by Django 4.2.16 on 2024-11-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_bid_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
