# Generated by Django 4.2.16 on 2025-01-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_application_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
