# Generated by Django 4.2.16 on 2025-03-11 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='items.car', verbose_name='Car'),
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_delivery', models.DateField()),
                ('date_return', models.DateField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_dates', to='items.application')),
            ],
        ),
    ]
