# Generated by Django 4.2.16 on 2025-03-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio', models.BooleanField(default=False)),
                ('audio_cd', models.BooleanField(default=False)),
                ('audio_mp3', models.BooleanField(default=False)),
                ('audio_usb', models.BooleanField(default=False)),
                ('audio_aux', models.BooleanField(default=False)),
                ('audio_bluetooth', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': 'Musics',
                'ordering': ['radio'],
            },
        ),
    ]
