# Generated by Django 4.2.16 on 2025-03-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_application_auto_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='air_conditioner',
            field=models.CharField(choices=[('Air conditioning', 'Air conditioning'), ('1-zone climate control', '1-zone climate control'), ('2-zone climate control', '2-zone climate control'), ('4-zone climate control', '4-zone climate control'), ('None', 'None')], max_length=128),
        ),
        migrations.AlterField(
            model_name='photo',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='files/documents_and_other/'),
        ),
    ]
