# Generated by Django 4.2.16 on 2025-03-16 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='music',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='items.music', verbose_name='Music'),
            preserve_default=False,
        ),
    ]
