# Generated by Django 4.2.16 on 2025-03-16 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_car_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_drivers_license', models.CharField(choices=[('A', 'A'), ('A1', 'A1'), ('A or B or M', 'A or B or M'), ('B', 'B'), ('B1', 'B1'), ('BE', 'BE'), ('M', 'M')], max_length=64)),
                ('seats', models.PositiveIntegerField()),
                ('doors', models.PositiveIntegerField()),
                ('air_conditioner', models.CharField(choices=[('Air conditioning', 'Air conditioning'), ('1-zone climate control', '1-zone climate control'), ('2-zone climate control', '2-zone climate control'), ('4-zone climate control', '4-zone climate control'), ('None', 'None')], max_length=128)),
                ('interior', models.CharField(choices=[('Fabric', 'Fabric'), ('Leather', 'Leather'), ('Sport', 'Sport'), ('Sport Leather', 'Sport Leather')], max_length=128)),
                ('roof', models.CharField(choices=[('Standard', 'Standard'), ('Sunroof', 'Sunroof'), ('Rigid foldable automatic', 'Rigid foldable automatic'), ('Soft foldable manual', 'Soft foldable manual'), ('Soft foldable automatic', 'Soft foldable automatic')], max_length=128)),
                ('powered_window', models.IntegerField(choices=[(2, 2), (4, 4)])),
                ('airbags', models.PositiveIntegerField()),
                ('side_wheel', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], max_length=64)),
                ('cruise_control', models.BooleanField(default=False)),
                ('rear_view_camera', models.BooleanField(default=False)),
                ('parking_assist', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='other',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='items.other', verbose_name='Other Features'),
            preserve_default=False,
        ),
    ]
