# Generated by Django 4.2.16 on 2025-03-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_other_car_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='aggregator',
            field=models.CharField(choices=[('Localrent', 'localrent'), ('Trip', 'trip'), ('Klook', 'klook'), ('Rentconnected', 'rentconnected')], max_length=128),
        ),
        migrations.AlterField(
            model_name='application',
            name='currency',
            field=models.CharField(choices=[('thb', 'thb'), ('usd', 'usd'), ('rub', 'rub')], max_length=256),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('Sedan', 'sedan'), ('Hatchback', 'hatchback'), ('Wagon', 'wagon'), ('Minivan', 'minivan'), ('Minibus', 'minibus'), ('Crossover', 'crossover'), ('Pickup', 'pickup'), ('Convertible', 'convertible'), ('Scooter', 'scooter'), ('Motorcycle', 'motorcycle'), ('ATV', 'atv'), ('Buggy', 'buggy'), ('Coupe', 'coupe')], max_length=128),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('White', 'white'), ('Black', 'black'), ('Grey', 'grey'), ('Red', 'red'), ('Blue', 'blue'), ('Green', 'green'), ('Yellow', 'yellow'), ('Brown', 'brown'), ('Beige', 'beige'), ('Orange', 'orange'), ('Silver', 'silver'), ('Sky blue', 'sky blue'), ('Purple', 'purple')], max_length=64),
        ),
        migrations.AlterField(
            model_name='chassis',
            name='drive',
            field=models.CharField(choices=[('Front wheel', 'front wheel'), ('Rear wheel', 'rear wheel'), ('4 wheels', '4 wheels')], max_length=64),
        ),
        migrations.AlterField(
            model_name='chassis',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'manual'), ('Automatic', 'automatic'), ('Automatic + Manual', 'automatic + manual')], max_length=64),
        ),
        migrations.AlterField(
            model_name='engine',
            name='fuel',
            field=models.CharField(choices=[('Benzin', 'benzin'), ('Dizel', 'dizel'), ('Hybrid', 'hybrid'), ('Turbo Dizel', 'turbo dizel'), ('Gaz', 'gaz'), ('Electricity', 'electricity')], max_length=64),
        ),
        migrations.AlterField(
            model_name='other',
            name='air_conditioner',
            field=models.CharField(choices=[('Air conditioning', 'air conditioning'), ('1-zone climate control', '1-zone climate control'), ('2-zone climate control', '2-zone climate control'), ('4-zone climate control', '4-zone climate control'), ('None', 'none')], max_length=128),
        ),
        migrations.AlterField(
            model_name='other',
            name='category_drivers_license',
            field=models.CharField(choices=[('A', 'a'), ('A1', 'a1'), ('A or B or M', 'a or b or m'), ('B', 'b'), ('B1', 'b1'), ('BE', 'be'), ('M', 'm')], max_length=64),
        ),
        migrations.AlterField(
            model_name='other',
            name='interior',
            field=models.CharField(choices=[('Fabric', 'fabric'), ('Leather', 'leather'), ('Sport', 'sport'), ('Sport Leather', 'sport leather')], max_length=128),
        ),
        migrations.AlterField(
            model_name='other',
            name='roof',
            field=models.CharField(choices=[('Standard', 'standard'), ('Sunroof', 'sunroof'), ('Rigid foldable automatic', 'rigid foldable automatic'), ('Soft foldable manual', 'soft foldable manual'), ('Soft foldable automatic', 'soft foldable automatic')], max_length=128),
        ),
        migrations.AlterField(
            model_name='other',
            name='side_wheel',
            field=models.CharField(choices=[('Left', 'left'), ('Right', 'right')], max_length=64),
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(choices=[('thb', 'thb'), ('usd', 'usd'), ('rub', 'rub')], max_length=10, null=True),
        ),
    ]
