# Generated by Django 4.2.16 on 2025-03-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_application_aggregator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='contact_type',
            field=models.CharField(choices=[('Phone', 'phone'), ('Telegram', 'telegram'), ('WhatsApp', 'whatsapp'), ('Viber', 'viber')], default='Telegram', max_length=64),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Closed', 'closed'), ('Expired', 'expired')], default='Active', max_length=128),
        ),
    ]
