# Generated by Django 4.2.16 on 2025-03-25 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_application_birthdate_application_client_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128)),
                ('is_expired', models.BooleanField(default=False)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128)),
                ('is_expired', models.BooleanField(default=False)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128)),
                ('is_expired', models.BooleanField(default=False)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Insurance',
            new_name='ACT',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='insurance',
            new_name='act',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='autumn_price',
            new_name='high_season',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='spring_price',
            new_name='low_season',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='summer_price',
            new_name='pick_season',
        ),
        migrations.RemoveField(
            model_name='price',
            name='car_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='winter_price',
        ),
        migrations.AddField(
            model_name='car',
            name='first_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_insurance', to='items.firstclass', verbose_name='Car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='second_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_insurance', to='items.secondclass', verbose_name='Car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='tax',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_insurance', to='items.tax', verbose_name='Car'),
            preserve_default=False,
        ),
    ]
