# Generated by Django 4.2.16 on 2025-03-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_firstclass_secondclass_tax_rename_insurance_act_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bluebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_expired', models.BooleanField(default=False)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('bluebook_image', models.ImageField(blank=True, null=True, upload_to='files/bluebook/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='engine',
            options={'verbose_name': 'Engine', 'verbose_name_plural': 'Engines'},
        ),
        migrations.RenameField(
            model_name='act',
            old_name='number',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='firstclass',
            old_name='number',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='secondclass',
            old_name='number',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tax',
            old_name='number',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='date',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='video',
        ),
        migrations.AddField(
            model_name='engine',
            name='power',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='misc',
            name='other_files',
            field=models.FileField(blank=True, null=True, upload_to='other_files/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='aggregator',
            field=models.CharField(choices=[('localrent', 'Localrent'), ('trip', 'Trip'), ('klook', 'Klook'), ('rentconnected', 'Rentconnected')], max_length=128),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_type',
            field=models.CharField(choices=[('phone', 'Phone'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('viber', 'Viber')], max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='currency',
            field=models.CharField(choices=[('THB', 'thb'), ('USD', 'usd'), ('RUB', 'rub')], max_length=256),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('expired', 'Expired')], default='Active', max_length=128),
        ),
        migrations.AlterField(
            model_name='car',
            name='act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_act', to='items.act', verbose_name='act'),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('wagon', 'Wagon'), ('minivan', 'Minivan'), ('minibus', 'Minibus'), ('crossover', 'Crossover'), ('pickup', 'Pickup'), ('convertible', 'Convertible'), ('scooter', 'Scooter'), ('motorcycle', 'Motorcycle'), ('atv', 'ATV'), ('buggy', 'Buggy'), ('coupe', 'Coupe')], max_length=128),
        ),
        migrations.AlterField(
            model_name='car',
            name='chassis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_chassis', to='items.chassis', verbose_name='Chassis'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('grey', 'Grey'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('brown', 'Brown'), ('beige', 'Beige'), ('orange', 'Orange'), ('silver', 'Silver'), ('sky blue', 'Sky blue'), ('purple', 'Purple')], max_length=64),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_engine', to='items.engine', verbose_name='Engine'),
        ),
        migrations.AlterField(
            model_name='car',
            name='first_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_first_class', to='items.firstclass', verbose_name='first_class'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_model', to='items.carmodel', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='music',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_music', to='items.music', verbose_name='Music'),
        ),
        migrations.AlterField(
            model_name='car',
            name='other',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_other', to='items.other', verbose_name='Other Features'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='cars_photos', to='items.photo', verbose_name='Photos'),
        ),
        migrations.AlterField(
            model_name='car',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='cars_problems', to='items.problem', verbose_name='Problems'),
        ),
        migrations.AlterField(
            model_name='car',
            name='second_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_second_class', to='items.secondclass', verbose_name='second_class'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_tax', to='items.tax', verbose_name='tax'),
        ),
        migrations.AlterField(
            model_name='chassis',
            name='drive',
            field=models.CharField(choices=[('front wheel', 'Front wheel'), ('rear wheel', 'Rear wheel'), ('4 wheels', '4 wheels')], max_length=64),
        ),
        migrations.AlterField(
            model_name='chassis',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('automatic + manual', 'Automatic + Manual')], max_length=64),
        ),
        migrations.AlterField(
            model_name='engine',
            name='fuel',
            field=models.CharField(choices=[('benzin', 'Benzin'), ('dizel', 'Dizel'), ('hybrid', 'Hybrid'), ('turbo dizel', 'Turbo Dizel'), ('gaz', 'Gaz'), ('electricity', 'Electricity')], max_length=64),
        ),
        migrations.AlterField(
            model_name='other',
            name='air_conditioner',
            field=models.CharField(choices=[('air conditioning', 'Air conditioning'), ('1-zone climate control', '1-zone climate control'), ('2-zone climate control', '2-zone climate control'), ('4-zone climate control', '4-zone climate control'), ('none', 'None')], max_length=128),
        ),
        migrations.AlterField(
            model_name='other',
            name='airbags',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], max_length=255),
        ),
        migrations.AlterField(
            model_name='other',
            name='category_drivers_license',
            field=models.CharField(choices=[('a', 'A'), ('a1', 'A1'), ('a or b or m', 'A or B or M'), ('b', 'B'), ('b1', 'B1'), ('be', 'BE'), ('m', 'M')], max_length=64),
        ),
        migrations.AlterField(
            model_name='other',
            name='doors',
            field=models.CharField(choices=[(2, 2), (4, 4)], max_length=255),
        ),
        migrations.AlterField(
            model_name='other',
            name='interior',
            field=models.CharField(choices=[('fabric', 'Fabric'), ('leather', 'Leather'), ('sport', 'Sport'), ('sport leather', 'Sport Leather')], max_length=128),
        ),
        migrations.AlterField(
            model_name='other',
            name='powered_window',
            field=models.CharField(choices=[(2, 2), (4, 4)], max_length=255),
        ),
        migrations.AlterField(
            model_name='other',
            name='roof',
            field=models.CharField(choices=[('standard', 'Standard'), ('sunroof', 'Sunroof'), ('rigid foldable automatic', 'Rigid foldable automatic'), ('soft foldable manual', 'Soft foldable manual'), ('soft foldable automatic', 'Soft foldable automatic')], max_length=128),
        ),
        migrations.AlterField(
            model_name='other',
            name='side_wheel',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=64),
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(choices=[('THB', 'thb'), ('USD', 'usd'), ('RUB', 'rub')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('toyota', 'Toyota'), ('bmw', 'BMW'), ('mercedes_benz', 'Mercedes-Benz'), ('audi', 'Audi'), ('ford', 'Ford'), ('chevrolet', 'Chevrolet'), ('honda', 'Honda'), ('nissan', 'Nissan'), ('hyundai', 'Hyundai'), ('volkswagen', 'Volkswagen')], max_length=128)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='items_carbr_name_875589_idx')],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='bluebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_bluebook', to='items.bluebook', verbose_name='bluebook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='items.carbrand', verbose_name='Brand'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
