# Generated by Django 4.2.16 on 2025-03-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_bluebook_alter_engine_options_rename_number_act_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, related_name='cars_photos', to='items.photo', verbose_name='Photos'),
        ),
        migrations.AlterField(
            model_name='car',
            name='problems',
            field=models.ManyToManyField(blank=True, null=True, related_name='cars_problems', to='items.problem', verbose_name='Problems'),
        ),
    ]
