# Generated by Django 4.2.16 on 2025-03-27 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_car_photos_alter_car_problems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='car',
            name='problems',
        ),
        migrations.AddField(
            model_name='car',
            name='photos',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars_photos', to='items.photo', verbose_name='Photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='problems',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars_problems', to='items.problem', verbose_name='Problems'),
            preserve_default=False,
        ),
    ]
