# Generated by Django 4.2.16 on 2025-03-27 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_remove_car_photos_remove_car_problems_car_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photos',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars_photos', to='items.photo', verbose_name='Photos'),
        ),
        migrations.AlterField(
            model_name='car',
            name='problems',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars_problems', to='items.problem', verbose_name='Problems'),
        ),
    ]
