# Generated by Django 4.2.16 on 2025-03-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_car_photos_alter_car_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='high_season',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='low_season',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='pick_season',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
