# Generated by Django 4.2.16 on 2025-03-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_price_high_season_alter_price_low_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='high_season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='low_season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='pick_season',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
