# Generated by Django 4.2.16 on 2025-03-27 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_alter_price_high_season_alter_price_low_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='items.price', verbose_name='Price'),
        ),
    ]
