# Generated by Django 4.2.16 on 2025-03-27 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_act', to='items.act', verbose_name='act'),
        ),
        migrations.AlterField(
            model_name='car',
            name='bluebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_bluebook', to='items.bluebook', verbose_name='bluebook'),
        ),
        migrations.AlterField(
            model_name='car',
            name='first_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_first_class', to='items.firstclass', verbose_name='first_class'),
        ),
        migrations.AlterField(
            model_name='car',
            name='second_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_second_class', to='items.secondclass', verbose_name='second_class'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_tax', to='items.tax', verbose_name='tax'),
        ),
    ]
