# Generated by Django 4.2.16 on 2025-03-31 15:33

from django.db import migrations, models
import django.db.models.deletion
import items.path_file


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_alter_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos_rel', to='items.car'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='car',
            name='photos',
        ),
        migrations.AlterField(
            model_name='misc',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to=items.path_file.applications_path),
        ),
        migrations.AlterField(
            model_name='misc',
            name='other_files',
            field=models.FileField(blank=True, null=True, upload_to=items.path_file.applications_path),
        ),
        migrations.AlterField(
            model_name='misc',
            name='vaucher',
            field=models.FileField(blank=True, null=True, upload_to=items.path_file.applications_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to=items.path_file.car_photo_upload_path),
        ),
        migrations.AddField(
            model_name='car',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='cars', to='items.photo'),
        ),
    ]
