# Generated by Django 4.2.16 on 2025-04-02 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_photo_car_remove_car_photos_alter_misc_contract_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': 'Music', 'verbose_name_plural': 'Musics'},
        ),
        migrations.RemoveField(
            model_name='act',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bluebook',
            name='name',
        ),
        migrations.RemoveField(
            model_name='firstclass',
            name='name',
        ),
        migrations.RemoveField(
            model_name='price',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='secondclass',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='name',
        ),
        migrations.AlterField(
            model_name='application',
            name='aggregator',
            field=models.CharField(choices=[('localrent', 'Localrent'), ('trip', 'Trip'), ('klook', 'Klook'), ('rentconnected', 'Rentconnected')], max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='client_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='currency',
            field=models.CharField(choices=[('THB', 'thb'), ('USD', 'usd'), ('RUB', 'rub')], max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='location_delivery',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='location_return',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('expired', 'Expired')], default='Active', max_length=64),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('wagon', 'Wagon'), ('minivan', 'Minivan'), ('minibus', 'Minibus'), ('crossover', 'Crossover'), ('pickup', 'Pickup'), ('convertible', 'Convertible'), ('scooter', 'Scooter'), ('motorcycle', 'Motorcycle'), ('atv', 'ATV'), ('buggy', 'Buggy'), ('coupe', 'Coupe')], max_length=64),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_brand', to='items.carbrand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(choices=[('toyota', 'Toyota'), ('bmw', 'BMW'), ('mercedes_benz', 'Mercedes-Benz'), ('audi', 'Audi'), ('ford', 'Ford'), ('chevrolet', 'Chevrolet'), ('honda', 'Honda'), ('nissan', 'Nissan'), ('hyundai', 'Hyundai'), ('volkswagen', 'Volkswagen')], max_length=64),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='other',
            name='air_conditioner',
            field=models.CharField(choices=[('air conditioning', 'Air conditioning'), ('1-zone climate control', '1-zone climate control'), ('2-zone climate control', '2-zone climate control'), ('4-zone climate control', '4-zone climate control'), ('none', 'None')], max_length=64),
        ),
        migrations.AlterField(
            model_name='other',
            name='airbags',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=64),
        ),
        migrations.AlterField(
            model_name='other',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('4', '4')], max_length=64),
        ),
        migrations.AlterField(
            model_name='other',
            name='interior',
            field=models.CharField(choices=[('fabric', 'Fabric'), ('leather', 'Leather'), ('sport', 'Sport'), ('sport leather', 'Sport Leather')], max_length=64),
        ),
        migrations.AlterField(
            model_name='other',
            name='powered_window',
            field=models.CharField(choices=[('2', '2'), ('4', '4')], max_length=64),
        ),
        migrations.AlterField(
            model_name='other',
            name='roof',
            field=models.CharField(choices=[('standard', 'Standard'), ('sunroof', 'Sunroof'), ('rigid foldable automatic', 'Rigid foldable automatic'), ('soft foldable manual', 'Soft foldable manual'), ('soft foldable automatic', 'Soft foldable automatic')], max_length=64),
        ),
        migrations.AlterField(
            model_name='photo',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_photos', to='items.car'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/'),
        ),
    ]
