# Generated by Django 4.2.16 on 2025-04-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_application_another_regions_application_baby_seat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='expired_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bluebook',
            name='expired_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firstclass',
            name='expired_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secondclass',
            name='expired_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='expired_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
