# Generated by Django 4.2.16 on 2025-04-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_alter_act_expired_at_alter_bluebook_expired_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='aggregator',
            new_name='agregator',
        ),
        migrations.AlterField(
            model_name='application',
            name='another_regions',
            field=models.CharField(choices=[('Southern provinces (Phuket, Phang Nga, Krabi-mainland)', 'southern provinces (phuket, phang nga, krabi-mainland)'), ('Islands (Phangan, Samui)', 'islands (phangan, samui)'), ('Central Provinces (Bangkok, Pattaya, Hua Hin)', 'central provinces (bangkok, pattaya, hua hin)'), ('Northern Provinces (Chiang Mai)', 'northern provinces (chiang mai)'), ('-', '-')], max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='baby_seat',
            field=models.CharField(choices=[('Baby seat low', 'baby seat low'), ('Baby seat high', 'baby seat high'), ('Booster', 'booster'), ('-', '-')], max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='complex_insurance',
            field=models.CharField(choices=[('Full insurance', 'full insurance'), ('Super Insurance', 'super insurance'), ('-', '-')], max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='url_delivery',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='url_return',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='other',
            name='air_conditioner',
            field=models.CharField(choices=[('Air conditioning', 'air conditioning'), ('1-zone climate control', '1-zone climate control'), ('2-zone climate control', '2-zone climate control'), ('4-zone climate control', '4-zone climate control'), ('-', '-')], max_length=64),
        ),
    ]
