# Generated by Django 4.2.16 on 2025-04-02 11:37

from django.db import migrations, models
import django.db.models.deletion
import items.path_file


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_rename_aggregator_application_agregator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='car',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_act', to='items.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bluebook',
            name='car',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_bluebook', to='items.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstclass',
            name='car',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_firstclass', to='items.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secondclass',
            name='car',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_secondclass', to='items.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tax',
            name='car',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_tax', to='items.car'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='another_regions',
            field=models.CharField(choices=[('Southern provinces (Phuket, Phang Nga, Krabi-mainland)', 'southern provinces (phuket, phang nga, krabi-mainland)'), ('Islands (Phangan, Samui)', 'islands (phangan, samui)'), ('Central Provinces (Bangkok, Pattaya, Hua Hin)', 'central provinces (bangkok, pattaya, hua hin)'), ('Northern Provinces (Chiang Mai)', 'northern provinces (chiang mai)'), ('-', '-')], default='-', max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='baby_seat',
            field=models.CharField(choices=[('Baby seat low', 'baby seat low'), ('Baby seat high', 'baby seat high'), ('Booster', 'booster'), ('-', '-')], default='-', max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='complex_insurance',
            field=models.CharField(choices=[('Full insurance', 'full insurance'), ('Super Insurance', 'super insurance'), ('-', '-')], default='-', max_length=64),
        ),
        migrations.AlterField(
            model_name='bluebook',
            name='bluebook_image',
            field=models.ImageField(blank=True, null=True, upload_to=items.path_file.bluebook_upload_path),
        ),
        migrations.AlterField(
            model_name='other',
            name='airbags',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')]),
        ),
        migrations.AlterField(
            model_name='other',
            name='doors',
            field=models.IntegerField(choices=[(2, '2'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='other',
            name='powered_window',
            field=models.IntegerField(choices=[(2, '2'), (4, '4')]),
        ),
    ]
