# Generated by Django 4.2.16 on 2025-04-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_act_car_bluebook_car_firstclass_car_secondclass_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misc',
            name='vaucher',
            field=models.FileField(blank=True, null=True, upload_to='vauchers/'),
        ),
    ]
