# Generated by Django 4.2.16 on 2025-04-05 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_alter_misc_vaucher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-id'], 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.AddField(
            model_name='application',
            name='rental_dates',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='application_rental_date', to='items.date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='high_season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='low_season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='pick_season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='number_of_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_date', to='items.application'),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
