# Generated by Django 4.2.16 on 2025-04-05 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_alter_application_options_remove_car_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='rental_dates',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_rental_date', to='items.date'),
        ),
    ]
