# Generated by Django 4.2.16 on 2025-04-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_alter_application_rental_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='another_regions',
            field=models.CharField(choices=[('-', '-'), ('Southern provinces (Phuket, Phang Nga, Krabi-mainland)', 'southern provinces (phuket, phang nga, krabi-mainland)'), ('Islands (Phangan, Samui)', 'islands (phangan, samui)'), ('Central Provinces (Bangkok, Pattaya, Hua Hin)', 'central provinces (bangkok, pattaya, hua hin)'), ('Northern Provinces (Chiang Mai)', 'northern provinces (chiang mai)')], default='-', max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='baby_seat',
            field=models.CharField(choices=[('-', '-'), ('Baby seat low', 'baby seat low'), ('Baby seat high', 'baby seat high'), ('Booster', 'booster')], default='-', max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='complex_insurance',
            field=models.CharField(choices=[('-', '-'), ('Full insurance', 'full insurance'), ('Super Insurance', 'super insurance')], default='-', max_length=64),
        ),
    ]
