# Generated by Django 4.2.16 on 2025-04-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0026_alter_application_another_regions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='number_of_days',
        ),
    ]
