# Generated by Django 4.2.16 on 2025-04-05 13:40

from django.db import migrations, models
import items.path_file


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0027_remove_date_number_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misc',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to=items.path_file.applications_path_for_other_contract),
        ),
        migrations.AlterField(
            model_name='misc',
            name='vaucher',
            field=models.FileField(blank=True, null=True, upload_to=items.path_file.applications_path_for_other_vaucher),
        ),
    ]
