# Generated by Django 4.2.16 on 2025-04-09 17:05

from django.db import migrations, models
import items.path_file


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0028_alter_misc_contract_alter_misc_vaucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to=items.path_file.car_photo_upload_path),
        ),
    ]
